name: easy_finemap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - attrs=22.1.0=pyh71513ae_1
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cachecontrol=0.12.11=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cleo=2.0.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - click-default-group=1.2.2=pyhd8ed1ab_1
  - conda-lock=1.0.5=pyhd8ed1ab_1
  - crashtest=0.4.1=pyhd8ed1ab_0
  - cryptography=38.0.4=py310h600f1e7_0
  - dbus=1.13.6=h5008d03_3
  - distlib=0.3.6=pyhd8ed1ab_0
  - dulwich=0.20.50=py310h1fa729e_0
  - ensureconda=1.4.3=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - filelock=3.8.2=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - html5lib=1.1=pyh9f0ad1d_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.10.1=pyhd8ed1ab_0
  - jaraco.classes=3.2.3=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - lockfile=0.12.2=py_1
  - markupsafe=2.1.1=py310h5764c6d_2
  - more-itertools=9.0.0=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py310hbf28c38_1
  - ncurses=6.3=h27087fc_1
  - numpy=1.24.0=py310h08bbf29_0
  - openssl=3.0.7=h0b41bf4_1
  - packaging=22.0=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pkginfo=1.9.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.0=pyhd8ed1ab_0
  - poetry=1.3.1=linux_pyhd8ed1ab_1
  - poetry-core=1.4.0=pyhd8ed1ab_0
  - poetry-plugin-export=1.2.0=pyhd8ed1ab_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.2=py310h5764c6d_1
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyrsistent=0.19.2=py310h5764c6d_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.8=h4a9ceb5_0_cpython
  - python_abi=3.10=3_cp310
  - pyyaml=6.0=py310h5764c6d_5
  - rapidfuzz=2.13.6=py310heca2aa9_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-toolbelt=0.10.1=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py310h5764c6d_2
  - ruamel.yaml.clib=0.2.7=py310h1fa729e_1
  - secretstorage=3.3.3=py310hff52083_1
  - setuptools=65.6.3=pyhd8ed1ab_0
  - shellingham=1.5.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.6=pyha770c72_0
  - trove-classifiers=2022.12.1=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - virtualenv=20.17.1=py310hff52083_0
  - webencodings=0.5.1=py_1
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.11.0=pyhd8ed1ab_0
  - pip:
    - black==22.12.0
    - bleach==5.0.1
    - bump2version==1.0.1
    - cfgv==3.3.1
    - colorama==0.4.6
    - commonmark==0.9.1
    - coverage==7.0.0
    - docutils==0.19
    - easy-finemap==0.0.1
    - easyfinemap==0.0.1
    - flake8==3.9.2
    - flake8-docstrings==1.6.0
    - ghp-import==2.1.0
    - griffe==0.25.0
    - identify==2.5.11
    - importlib-metadata==5.2.0
    - iniconfig==1.1.1
    - isort==5.11.3
    - keyring==23.13.1
    - markdown==3.3.7
    - mccabe==0.6.1
    - mergedeep==1.3.4
    - mkdocs==1.4.2
    - mkdocs-autorefs==0.4.1
    - mkdocs-include-markdown-plugin==4.0.3
    - mkdocs-material==8.5.11
    - mkdocs-material-extensions==1.1.1
    - mkdocstrings==0.19.1
    - mkdocstrings-python==0.8.2
    - mypy==0.900
    - mypy-extensions==0.4.3
    - nodeenv==1.7.0
    - pandas==1.5.2
    - pathspec==0.10.3
    - pip==20.3.4
    - pluggy==1.0.0
    - pre-commit==2.20.0
    - py==1.11.0
    - pycodestyle==2.7.0
    - pydocstyle==6.1.1
    - pyflakes==2.3.1
    - pygments==2.13.0
    - pymdown-extensions==9.9
    - pytest==6.2.5
    - pytest-cov==2.12.1
    - python-dateutil==2.8.2
    - pytkdocs==0.11.1
    - pytz==2022.7
    - pyyaml-env-tag==0.1
    - readme-renderer==37.3
    - rfc3986==2.0.0
    - rich==12.6.0
    - snowballstemmer==2.2.0
    - tox==3.28.0
    - tqdm==4.64.1
    - twine==3.8.0
    - typer==0.7.0
    - watchdog==2.2.0
prefix: /beegfs/home/wangjianhua/anaconda3/envs/easy_finemap
