name: easyfinemap
channels:
  - dnachun
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - bcftools=1.17=h3cc50cf_1
  - binutils_impl_linux-64=2.40=hf600244_0
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=h0c91306_1017
  - caviarbf=1.0=h2bc3f7f_0
  - cffi=1.15.1=py311hb3a22ac_5
  - curl=8.3.0=hca28451_0
  - expat=2.5.0=hcb278e6_1
  - finemap=1.4.1=0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=13.2.0=h338b0a0_2
  - gcta=1.94.1=h9ee0642_0
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=13.2.0=h76e1118_2
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=13.2.0=h338b0a0_2
  - harfbuzz=8.2.1=h3d44ed6_0
  - htslib=1.18=h81da01d_0
  - icu=73.2=h59595ed_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=18_linux64_openblas
  - libcblas=3.9.0=18_linux64_openblas
  - libcurl=8.3.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=13.2.0=ha9c7c90_2
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=18_linux64_openblas
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libsanitizer=13.2.0=h7e041cc_2
  - libsqlite=3.43.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=13.2.0=ha9c7c90_2
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.6.0=h29866fb_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - make=4.3=hd18ef5c_1
  - markupsafe=2.1.3=py311h459d7ec_1
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.3=hd590300_0
  - paintor=3.1=h2bc3f7f_0
  - pango=1.50.14=ha41ecd1_2
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=4_hd590300_perl5
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - plink=1.90b6.21=h031d066_5
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - python=3.11.5=hab00c5b_0_cpython
  - python_abi=3.11=4_cp311
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - r-base=4.3.1=h639d9d3_5
  - r-cli=3.6.1=r43ha503ecb_1
  - r-codetools=0.2_19=r43hc72bb7e_1
  - r-colorspace=2.1_0=r43h57805ef_1
  - r-crayon=1.5.2=r43hc72bb7e_2
  - r-data.table=1.14.8=r43h029312a_2
  - r-ellipsis=0.3.2=r43h57805ef_2
  - r-fansi=1.0.4=r43h57805ef_1
  - r-farver=2.1.1=r43ha503ecb_2
  - r-foreach=1.5.2=r43hc72bb7e_2
  - r-ggplot2=3.4.3=r43hc72bb7e_0
  - r-glmnet=4.1_8=r43hcf54a89_0
  - r-glue=1.6.2=r43h57805ef_2
  - r-gtable=0.3.4=r43hc72bb7e_0
  - r-irlba=2.3.5.1=r43h316c678_1
  - r-isoband=0.2.7=r43ha503ecb_2
  - r-iterators=1.0.14=r43hc72bb7e_2
  - r-labeling=0.4.3=r43hc72bb7e_0
  - r-lattice=0.21_8=r43h57805ef_1
  - r-lifecycle=1.0.3=r43hc72bb7e_2
  - r-magrittr=2.0.3=r43h57805ef_2
  - r-mass=7.3_60=r43h57805ef_1
  - r-matrix=1.6_1.1=r43h316c678_0
  - r-matrixstats=1.0.0=r43h57805ef_1
  - r-mgcv=1.9_0=r43h316c678_0
  - r-mixsqp=0.3_48=r43h08d816e_1
  - r-munsell=0.5.0=r43hc72bb7e_1006
  - r-nlme=3.1_163=r43h61816a4_0
  - r-pillar=1.9.0=r43hc72bb7e_1
  - r-pkgconfig=2.0.3=r43hc72bb7e_3
  - r-plyr=1.8.8=r43ha503ecb_1
  - r-r6=2.5.1=r43hc72bb7e_2
  - r-rcolorbrewer=1.1_3=r43h785f33e_2
  - r-rcpp=1.0.11=r43h7df8631_0
  - r-rcpparmadillo=0.12.6.4.0=r43h08d816e_0
  - r-rcppeigen=0.3.3.9.3=r43h08d816e_1
  - r-reshape=0.8.9=r43hc72bb7e_2
  - r-rlang=1.1.1=r43ha503ecb_1
  - r-scales=1.2.1=r43hc72bb7e_2
  - r-shape=1.4.6=r43ha770c72_2
  - r-survival=3.5_7=r43h57805ef_0
  - r-susier=0.12.35=r43hc72bb7e_1
  - r-tibble=3.2.1=r43h57805ef_2
  - r-utf8=1.2.3=r43h57805ef_1
  - r-vctrs=0.6.3=r43ha503ecb_0
  - r-viridislite=0.4.2=r43hc72bb7e_1
  - r-withr=2.5.0=r43hc72bb7e_2
  - readline=8.2=h8228510_1
  - rpy2=3.5.11=py311r43h1f0f07a_2
  - sed=4.8=he412f7d_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - simplegeneric=0.8.1=py_1
  - sysroot_linux-64=2.12=he073ed8_16
  - tk=8.6.13=h2797004_0
  - tktable=2.10=h0c5db8f_4
  - tzdata=2023c=h71feb2d_0
  - tzlocal=5.0.1=py311h38be061_1
  - wheel=0.41.2=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.11.0
      - dill==0.3.7
      - easyfinemap==0.4.4
      - fonttools==4.42.1
      - idna==3.4
      - kiwisolver==1.4.5
      - liftover==1.1.16
      - markdown-it-py==3.0.0
      - matplotlib==3.8.0
      - mdurl==0.1.2
      - multiprocess==0.70.15
      - numpy==1.26.0
      - packaging==23.1
      - pandas==1.5.3
      - pathos==0.3.1
      - pillow==10.0.1
      - pox==0.3.3
      - ppft==1.7.6.7
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pytabix==0.1
      - python-dateutil==2.8.2
      - requests==2.31.0
      - rich==13.5.3
      - scipy==1.11.2
      - six==1.16.0
      - smunger==0.1.5
      - typer==0.7.0
      - urllib3==1.26.15
prefix: /mnt/hpc/home/wangjianhua/mambaforge/envs/easyfinemap
